--- # Fast Start :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: apps/v1    
kind: Deployment
metadata:
  name: crimson-house
  namespace: crimson
  labels:
    app: crimson-house
spec:
  selector:
    matchLabels:
      app: crimson-house
  replicas: 1
  template:
    metadata:
      labels:
        app: crimson-house
    spec:
      containers:
      - name: crimson-house
        image: ibmicpcoc/house:latest
        imagePullPolicy: Always
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: <team>-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: <team>-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
